version: '2'
services:
    ethsearch-app:
        image: ethsearch
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://ethsearch-mariadb:3306/ethsearch
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://ethsearch-elasticsearch:9200
        ports:
            - 8080:8080
    ethsearch-mariadb:
        extends:
            file: mariadb.yml
            service: ethsearch-mariadb
    ethsearch-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ethsearch-elasticsearch
